### ISSUE TITLE
Out Of Memory for multiple model trainings + validations

### ISSUE THREAD

**Issue by NickHauptvogel** [deephealthproject/pyeddl#63]
Hi,

I am trying to tune the hyperparameters of my model via a simple grid search strategy (basically a for loop) with different configurations. Each iteration, a model is created, built with `eddl.build` and trained afterwards. However, after training one model, the creation of the next model crashes with a 'cuda out of memory' error. 
Looking at nvidia-smi, the memory does not seem to be released after training the model, causing the GPU to crash when creating the next model. I've found some memory-related issues in the [EDDL ](https://github.com/deephealthproject/eddl) repository, but all of them are closed.

Do I need to call anything after training + validation in order to free the memory?

I am using a custom model (Stacked Hourglass) that is attached in .onnx format.
[model.zip](https://github.com/deephealthproject/pyeddl/files/6598803/model.zip)

KR,

Nick

**Comment by simleo** [comment]
Hi. Please post the full Python code you're running.

**Comment by NickHauptvogel** [comment]
Hi, the full code would be quite much, however, I can give you the relevant extracts to determine what is going wrong. 

The relevant function is `fit` in `EDDLConvolutionalModel.py`, which calls `train_batch` and `evaluate`  for the whole data set for the given number of epochs. Afterwards, the for loop in `Trainer.py` returns the next hyperparameter configuration, but the next model can't be built (in  the factory `ConvolutionalModelFactory`) due to the full GPU memory. 

Hope that helps!

KR, Nick

Code from: `Trainer.py`
```

# Iterate via all Hyperparameter Configurations
for model_config_dict, training_config_dict in self.hp.get_configs():

    name = datetime.now().strftime('%Y%m%d_%H%M')
    logging.info(f'MODEL NAME: {name}')

    # Create Training Config
    training_config = TrainingConfigFactory.create_training_config(copy.deepcopy(training_config_dict))
    training_config.log_config()
    early_stopping = training_config.get_cb_early_stopping()
    reduce_lr = training_config.get_cb_reduce_lr_on_plateau()

    # Create ConvolutionalModel to train
    model, initial_lr = ConvolutionalModelFactory.create_convolutional_model(width=self.width,
                                                                             height=self.height,
                                                                             input_channels=self.input_channels,
                                                                             output_channels=self.output_channels,
                                                                             gpu=gpu,
                                                                             model_config=copy.deepcopy(
                                                                                 model_config_dict))
    model.log_config()

    # Fit model
    history = model.fit(train_data,
                        train_labels,
                        val_data,
                        val_labels,
                        training_config.get_epochs(),
                        training_config.get_batch_size(),
                        initial_lr,
                        reduce_lr,
                        early_stopping)

```
Code from `EDDLConvolutionalModel.py`

```

    def fit(self,
            train_data: List[np.array],
            train_labels: List[np.array],
            val_data: List[np.array],
            val_labels: List[np.array],
            epochs: int,
            batch_size: int,
            initial_lr: float,
            reduce_lr: CallbackReduceLROnPlateau,
            early_stopping: CallbackEarlyStopping) -> Dict:
        """
        Performs fitting of the built model in EDDL
        :param train_data: training input images
        :param train_labels: training heatmaps
        :param val_data: validation input images
        :param val_labels: validation heatmaps
        :param epochs: number of epochs to train
        :param batch_size: batch size
        :param initial_lr: initial learning rate in the training
        :param reduce_lr: CallbackReduceLROnPlateau to reduce learning rate
        :param early_stopping: CallbackEarlyStopping to stop the training with no improvement
        :return: history of 'training_losses', 'training_metrics', 'validation_losses', 'validation_losses_medians',
        'validation_metrics', 'validation_metrics_medians', 'learning_rates'
        """

        training_losses = []
        training_metrics = []
        validation_losses = []
        validation_losses_medians = []
        validation_metrics = []
        validation_metrics_medians = []
        learning_rates = [initial_lr]

        logging.info(f'\n============== TRAINING ==============\n')
        for i in range(epochs):
            logging.info(f'\n-------------- EPOCH {i + 1}/{epochs} --------------\n')

            eddl.reset_loss(self.built_model)

            training_loss, training_metric, _, _ = self.__execute_per_data_set(train_data,
                                                                               train_labels,
                                                                               eddl.train_batch,
                                                                               batch_size=batch_size)

            eddl.reset_loss(self.built_model)

            val_loss, val_metric, val_loss_median, val_metric_median = self.__execute_per_data_set(val_data,
                                                                                                   val_labels,
                                                                                                   eddl.evaluate,
                                                                                                   batch_size=batch_size)

            training_losses.append(training_loss)
            training_metrics.append(training_metric)
            validation_losses.append(val_loss)
            validation_losses_medians.append(val_loss_median)
            validation_metrics.append(val_metric)
            validation_metrics_medians.append(val_metric_median)

            # Apply callbacks
            changed, new_lr = reduce_lr.compute_new_lr(validation_losses_medians[-1], learning_rates[-1])
            if changed:
                eddl.setlr(self.built_model, [new_lr])
            learning_rates.append(new_lr)

            if early_stopping.apply(validation_losses_medians[-1]):
                break

        logging.info(f'\n============== END TRAINING ==============\n')

        history = {
            'training_losses': training_losses,
            'training_metrics': training_metrics,
            'validation_losses': validation_losses,
            'validation_losses_medians': validation_losses_medians,
            'validation_metrics': validation_metrics,
            'validation_metrics_medians': validation_metrics_medians,
            'learning_rates': learning_rates
        }

        return history

    def evaluate(self,
                 test_data: List[np.array],
                 test_labels: List[np.array],
                 batch_size: int) -> Tuple[float, float, float, float]:
        """
        Evaluates the built model on a given test set in EDDK
        :param test_data: test input images
        :param test_labels: test heatmaps
        :param batch_size: batch size
        :return: test_loss, test_metric, test_loss_median, test_metric_median
        """

        test_loss, test_metric, test_loss_median, test_metric_median = self.__execute_per_data_set(test_data,
                                                                                                   test_labels,
                                                                                                   eddl.evaluate,
                                                                                                   batch_size)

        return test_loss, test_metric, test_loss_median, test_metric_median

    def __execute_per_data_set(self,
                               x: List[np.array],
                               y: List[np.array],
                               method: Callable,
                               batch_size: int) -> Tuple[float, float, float, float]:
        """
        Execute a given method for each batch on a given data set
        :param x: data set to apply method on
        :param y: labels of the data set
        :param method: Callable to apply
        :param batch_size: batch size to divide the data set
        :return: loss average, metric average, loss median, metric median across the data set
        """

        x_size = len(x)
        # Determine number of batches to skip for logging
        checkpoint = max(x_size // 100, 1)
        num_batches = x_size // batch_size
        logging.info(f'Executing {method.__name__} ({num_batches} batches)')

        losses = []
        metrics = []
        for j in range(num_batches):

            x_tensor = Tensor.fromarray(x[j * batch_size:(j + 1) * batch_size])
            y_tensor = Tensor.fromarray(y[j * batch_size:(j + 1) * batch_size])

            method(self.built_model, [x_tensor], [y_tensor] * len(self.losses))
            loss1 = eddl.get_losses(self.built_model)
            metric1 = eddl.get_metrics(self.built_model)
            losses.append(sum(loss1) / len(loss1))
            metrics.append(sum(metric1) / len(metric1))
            if j % checkpoint == 0:
                logging.info(f'Batch: {j + 1} Loss: {loss1} Metric: {metric1}')

        return statistics.mean(losses), statistics.mean(metrics), statistics.median(losses), statistics.median(metrics)

    def predict(self, image: np.array) -> Tuple[np.array, float]:
        """
        Makes a prediction for a given image in EDDL
        :param image: image to predict
        :return: prediction as (width, height, output_channels), execution time of inference
        """
        x_tensor = Tensor.fromarray([image])

        start_time = time.time()
        pred = eddl.predict(self.built_model, [x_tensor])
        execution_time = time.time() - start_time

        pred = Tensor.getdata(pred[-1])[0]

        # Make sure that output channels are third dimension: (width, height, output_channels)
        if len(pred[:, 0, 0]) == self.output_channels:
            pred = np.transpose(pred, [1, 2, 0])

        return pred, execution_time

```

**Comment by simleo** [comment]
> Hi, the full code would be quite much

No need to post the actual code, you can just post a link to the repository.

The reason why I asked to see the full code was to look for references to the model (`Net`) object. Pyeddl takes ownership of `Net` objects, so they have to be released at the Python level. However, in Python, actually releasing memory is not up to the programmer: instead, the garbage collector automatically deallocates an object when its reference count drops to zero. To avoid memory issues, you need to make sure that there are no references left to the old model when you create a new one. A good way to achieve this is to reassign the variable that points to the model. For instance:

```python
import pyeddl.eddl as eddl

for lr in 0.01, 0.001:
    in_ = eddl.Input([784])
    layer = in_
    layer = eddl.LeakyReLu(eddl.Dense(layer, 1024))
    layer = eddl.LeakyReLu(eddl.Dense(layer, 1024))
    layer = eddl.LeakyReLu(eddl.Dense(layer, 1024))
    out = eddl.Softmax(eddl.Dense(layer, num_classes), -1)
    net = eddl.Model([in_], [out])
    eddl.build(net, eddl.rmsprop(lr), ["soft_cross_entropy"],
               ["categorical_accuracy"], eddl.CS_GPU())
    # training code here
```

The above program should use more or less the same memory at each iteration, since `net` is reassigned to a new model and the old one is left with no references to it. From what I've seen, it looks like your situation is a bit more complicated, with custom Python-level classes that probably hold references to model objects themselves. Basically, however, you need to check that *all* references to the old model object are dropped when you move to the next iteration.

**Comment by NickHauptvogel** [comment]
Hi Simone,

thanks for your comment, you had the correct intuition! I kept the best model in memory, which caused the memory to overflow when creating the next model! By explicitly setting the net variable to `None`, this issue is fixed!

Thank you and kind regards!
